---
- block:
  - name: make www folder structure
    ansible.builtin.file:
      path: "/var/www/html/js"
      state: directory
      owner: "www-data"
      group: "www-data"
      mode: ug=rwX,o=rX

  - name: "Render html files"
    ansible.builtin.template:
      src: "index.html.j2"
      dest: "/var/www/html/index.html"
      owner: "www-data"
      group: "www-data"
      mode: '0644'

  - name: "Render js files"
    ansible.builtin.template:
      src: "index.js.j2"
      dest: "/var/www/html/js/index.js"
      owner: "www-data"
      group: "www-data"
      mode: '0644'

  - name: Start httpd service
    ansible.builtin.systemd:
      name: apache2
      state: started
      daemon_reload: no
      enabled: yes
