---
- block:
  - name: make www folder structure
    ansible.builtin.file:
      path: "/var/www/html/js"
      state: directory
      owner: "www-data"
      group: "www-data"
      mode: ug=rwX,o=rX
    when: req_installed.stat.exists == false

  - name: "Render html files"
    ansible.builtin.template:
      src: "{{ item }}.j2"
      dest: "/var/www/html/{{ item }}"
      owner: "www-data"
      group: "www-data"
      mode: '0644'
    loop:
      - index.html
      - index2.html

  - name: "Render js files"
    ansible.builtin.template:
      src: "{{ item }}.j2"
      dest: "/var/www/html/js/{{ item }}"
      owner: "www-data"
      group: "www-data"
      mode: '0644'
    loop:
      - index.js
      - index2.js

  - name: Start httpd service
    ansible.builtin.systemd:
      name: apache2
      state: started
      daemon_reload: no
      enabled: yes
