---
# install all
- hosts: "{{ host }}"
  become: yes
  max_fail_percentage: 0
  tasks:
    - block:

      - include_role:
          name: common
        tags:
        - always

      - include_role:
          name: berrybase-hdt22.py
        tags:
          - always

      - include_role:
          name: berrybase-hdt22-webinterface
        tags:
          - always
