---
- name: "install apt pkg's"
  ansible.builtin.apt:
    pkg: "{{ apt_pkgs }}"
  tags:
    - always

- name: Install python pip modules
  ansible.builtin.pip:
    name:
      - pip 
      - setuptools 
      - wheel
      - Adafruit_DHT
    state: latest
  tags:
    - always
