---
- block:
  - name: check if requirements are already initialized
    ansible.builtin.stat:
      path: "{{ install_path }}/.requirements.ok"
    register: req_installed

  - name: "install apt pkg's"
    ansible.builtin.apt:
      pkg: "{{ apt_pkgs }}"
      state: present
      update_cache: yes
      update_cache_retries: 2
      upgrade: no
    when: req_installed.stat.exists == false
    tags:
      - always

  - name: Install python pip modules
    ansible.builtin.pip:
      name:
        - pip 
        - setuptools 
        - wheel
        - Adafruit_DHT
      state: latest
    when: req_installed.stat.exists == false
    tags:
      - always

  - name: Create "{{ install_path }}/.requirements.ok"
    ansible.builtin.file:
      path: "{{ install_path }}/.requirements.ok"
      state: touch
      owner: "{{ py_user }}"
      group: "{{ py_user }}"
      mode: '0644'
